# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='timeend',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='timest',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
