# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_auto_20161204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftslots',
            name='shiftId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='shift.Shifts'),
        ),
    ]
