# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 06:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_auto_20161205_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftslots',
            name='userId',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
